garabik/grc

conf.df
Fix df "Filesystem" header being colored.
Fix Mounted on regex
=> Fix df header being colored

conf.ifconfig
* Add IPv6 prefix support.
* Add iface vlan support.
=> Modifing conf.ifconfig. Added new features

grc.conf
=> add journalctl command

conf.dockerimages, conf.dockerps, grc.conf
I found a few issues with the new docker ps config. It didn't format right for me and it looked to be a little over fitted. Let me know @iax7 if you see any issues (or anyone else)
This is what is should look like:
=> Docker-ps: Fixing some edge cases and generalizing

INSTALL
=> Add homebrew install instructions & fix typo

conf.dockerimages, conf.dockerps, grc.conf
Adds docker-compose in with docker-ps and fixes some issues with it.
Also added color for the command in docker-compose ps.
Extension of #29
=> Update docker ps and docker-compose ps regex.

conf.netstat
=> Support matching for IPv6 versions of tcp & udp

conf.gcc, grc.conf
=> Support more coloring around gcc

conf.configure
=> More advanced regex for configure colouring

grc, grcat
=> Convert for py3 compatibility

README.markdown, grc.fish
Some slight improvements, mostly to the fish shell integration.
=> Improved shell integration and instructions

conf.ls
Also made Time and Month regex slightly more specific to avoid false positives.
=> Coloring file sizes in ls -l and ls -lh

colourfiles/conf.df, grc.bashrc
Come on, wussies!  You don't know if a disk truly loves you, until you've pushed her past 95%!
=> Missing Separator

grc.zsh
=> Consider existing aliases when defining aliases in zsh

README.markdown
Based on: https://unix.stackexchange.com/questions/148/colorizing-your-terminal-and-shell-environment
=> Add "Dynamic aliases"

colourfiles/conf.ping
Works with
0%
0.0%
100%
100.0%
=> Fix packet loss percent with dot number

colourfiles/conf.kubectl, grc.conf
Improve compatibility with `kubrectl describe` and added a few more "red words"
=> small improvements

colourfiles/conf.log, grc.bashrc, grc.fish
Thanks for a cool tool!!
This is for Issue 155.
=> Support for FQDNs, and add the journalctl alias to the grc.bash and grc.fish

colourfiles/conf.sockstat, grc.bashrc, grc.conf, grc.fish, grc.zsh
=> add support for FreeBSD's sockstat command

grc.zsh
Tweaks after review from an fluent speaker of zsh :) 
Ref:
- https://github.com/garabik/grc/commit/98f483068a817afccb29572c25f120ea06b4c6b6#r45477503
- #172
- ohmyzsh/ohmyzsh#9553
=> Changes as per review.
