README, conf.df, grc.bashrc
Add support for Ki, Mi, Gi and Ti (Mac OS X / Darwin uses these units instead of K, M, G and T)
=> Add support for Ki, Mi, Gi and Ti

conf.ifconfig
(verified to still work on Linux).
Added 0-9 for main interface name because of interfaces like p2p0. 
Example ifconfig output:
```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
options=3<RXCSUM,TXCSUM>
inet6 ::1 prefixlen 128
inet 127.0.0.1 netmask 0xff000000
inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
nd6 options=1<PERFORMNUD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
ether 02:03:08:8c:ba:92
media: autoselect
status: inactive
```
=> Support ifconfig interface highlighting also on BSD systems 

conf.df
Fixes highlighting in cases like this:
```
overlaid         4052872    152284   3900588    4% /tmp/duncan-firefox-kmx5veqj.default
```
=> conf.df: fix mounted on

grc, grcat
If /usr/bin/python is too old, `grcat` occurs the error below.
```bash
$ grcat
File "/usr/local/bin/grcat", line 252
except IOError as e:
^
SyntaxError: invalid syntax
```
This patch is to specify `/usr/bin/env python` in the shebang and use your newer python.
=> use env python

conf.ip
This adds colouring for the "ip" command.
I optimised it for the call "ip r" (show local routing table), but colourings should
be helpful for other parameters and modi too.
It could also be helpful for the route command, I didn't test.
About regexes: I'm used too perl regexes and it seems like python regexes are fully compatible :) [1]
Perhaps a good info for contributors and the README.
Links:
[1] https://docs.python.org/2/howto/regex.html
=> Add   conf.ip  for   "ip"   command

grc.bashrc
This pull request adds traceroute6 alias, ifconfig alias, and removes absolute path from /usr/sbin/traceroute since some distros (i.e. Slackware) put it on /usr/bin instead.
Feel free to cherry pick, or let me know if you want me to split it up.
Thanks :)
=> Traceroute6 and others

grc, grc.conf, grcat
Search for config file in `${XDG_CONFIG_HOME}/.grc` (or `~/.config/grc` when the variable is not set).
The directory `~/.grc` is still supported as a fallback, so this change is backwards-compatible.
I also made it so the configuration file is looked at `/usr/local/etc` in addition to `/etc`.
=> Support the XDG Base Directory Specification

README.markdown, grcat, grcat.1
This is primarily intended to produce _errors_ and _warning_ files that can be opened with
`vim -q errors.txt`
This allows us to build large projects from the command line, filtering out certain errors and warnings into files that we can investigate afterwards when necessary, without building directly from vim.
=> Added 'concat' option for appending matches to a file

conf.ant, conf.mvn, grc.conf
Configuration for Apache Ant and Apache Maven building systems.
This is how maven build looks with colorizing:
=> configuration for ant and maven

grc.bashrc
which is an external tool, where as type is a bash internal funciton
and always available
=> Use bash internal functionalities for grc detection

grc.bashrc
fixed typo on getsebool which was aliased to setsebool
alias getsebool='colourify setsebool'
=> Fixed getsebool typo

_grc, grc.zsh, install.sh
Using the `_sudo` function as a reference, I have written a completion function for grc.  This is helpful not only when calling grc directly, but when Zsh resolves completions for aliases.  We can now unset COMPLETE_ALIASES, which allows Zsh's completion system to be used to its fullest.
=> Support ZSH auto-completion

grc.bashrc, grc.fish, grc.zsh
I would like to wrap the [`docker-compose` command](https://github.com/garabik/grc/blob/master/grc.conf#L172) in the colourizer, so its output is automatically colourized, just like `docker`.
This should get rid of the cognitive overhead of having `grc docker-compose ps` vs. `docker ps`
=> Add docker-compose to the shell init files

colourfiles/conf.common, colourfiles/conf.dig, colourfiles/conf.ipaddr, colourfiles/conf.iproute, colourfiles/conf.uptime
This commit fix colors for dig, ip addr, ip route, and uptime commands. 
Adds a common color file for commands where some statuses can be highlighted in gree, red, yellow colors. This was tested with kubectl and minikube commands, but can be used with many others. This common file was purposely left out of config files.
=> Fix color files

colourfiles/conf.log
This commit refines how logfiles are displayed, so it is more suitable for webserver and mailserver logs in addition to generic kernel messages:
* Add colorization of strings in double quotes
* Alter parsing of pathnames to also include common URL path components
* Mark IPv4 and IPv6 addresses
* Detect email addresses
* Detect HTTP verbs and common HTTP and mailserver status codes
I think it is rather nice to look at and easy to visually parse important parts of each log line. Since I've been using this config for a long time on my servers I thought I should give back and make it available to the public.
Merge if you feel like it, if not it is here to copy for anyone that wants to. Thanks @garabik for your awesome tool!
=> Update logfile config

colourfiles/conf.iwconfig
Hi
On stretch debian, iwconfig shows : 
```
enp1s0    no wireless extensions.
lo        no wireless extensions.
enp3s0    no wireless extensions.
wlx002275d82e09  IEEE 802.11  ESSID:"CFA_UTEC"
Mode:Managed  Frequency:2.412 GHz  Access Point: 00:59:DC:89:D2:A0
Bit Rate=43.3 Mb/s   Tx-Power=20 dBm
Retry short  long limit:2   RTS thr:off   Fragment thr:off
Power Management:off
Link Quality=35/70  Signal level=-75 dBm
Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
Tx excessive retries:0  Invalid misc:0   Missed beacon:0
```
Then Bit Rate can contain dots.
=> iwconfig : Bit Rate can contain dots : Bit Rate=43.3 Mb/s

colourfiles/conf.uptime
So load averages also are colourised when e.g. LANG=es_ES
=> conf.uptime: Support decimal comma

_grc
"color" was used in the zsh completion, which means `grc --colour=auto docker` won't complete because of it.
=> Fix zsh completions if --colour is used

grc.conf
Add 'image ls' and 'image list' as alternatives to 'images'.
'docker image ls' and 'docker image list' are aliases for 'docker images', colourise them as well.
=> grc.conf: Expand conf.dockerimages regex

colourfiles/conf.du
1) du without -h is now supported.
2) du -h can output a 2-digit file size, eg " 25MB", and will have a space character for padding, and this is now accounted for.
=> Fixing du colorization

grc
According to issue #135,  if the user creates a user-specific configuration the system-wide configuration stops working.
This PR changes the order to system-then-user.
The latest found takes precedence.
=> Change configuration order to sytem-then-user

colourfiles/conf.go-test, grc.conf
Fixes #122.
Adds support for `go test`.
=> Add support for `go test`

colourfiles/conf.traceroute, grc.conf
- accept parameters between "ip" and main parameter
- accept all correct syntax of "address" ("a", "ad", "add", "addr", "addre",...,"address")
- do the the same with "link", "route" and "neighbour"
=> grc.conf : command ip and traceroute :

colourfiles/conf.dockerps
The old regex didn't like port ranges and a few other cases.
Unpatched/current formatting on top, patched below:
=> docker ps: ip addresses and ports colorization

colourfiles/conf.log
Example of file, from the command : lsblk -n -P -p -o HOTPLUG,MOUNTPOINT,STATE,NAME,TYPE,FSTYPE
>----------------------------
HOTPLUG="0" MOUNTPOINT="/usr/lib/live/mount/rootfs/filesystem.squashfs" STATE="" NAME="/dev/loop0" TYPE="loop" FSTYPE="squashfs"
HOTPLUG="0" MOUNTPOINT="" STATE="running" NAME="/dev/sda" TYPE="disk" FSTYPE=""
HOTPLUG="0" MOUNTPOINT="" STATE="" NAME="/dev/sda1" TYPE="part" FSTYPE="vfat"
HOTPLUG="0" MOUNTPOINT="" STATE="" NAME="/dev/sda2" TYPE="part" FSTYPE=""
HOTPLUG="0" MOUNTPOINT="" STATE="" NAME="/dev/sda3" TYPE="part" FSTYPE="ntfs"
HOTPLUG="1" MOUNTPOINT="" STATE="running" NAME="/dev/sdb" TYPE="disk" FSTYPE="iso9660"
HOTPLUG="1" MOUNTPOINT="/usr/lib/live/mount/medium" STATE="" NAME="/dev/sdb1" TYPE="part" FSTYPE="iso9660"
HOTPLUG="1" MOUNTPOINT="" STATE="" …
=> conf.log : accept now empty string "" and empty parentheses ()

colourfiles/conf.log
With this log (from journalctl of openvpn, except the last line)
```
Dec 12 12:19:40 VPN ovpn-Serveur[355]: Initialization Sequence Completed
Dec 12 12:19:41 VPN ovpn-Serveur[355]: TCP connection established with [AF_INET]172.16.1.100:56364
Dec 12 12:19:41 VPN ovpn-Serveur[355]: 172.16.1.100:56364 TCP connection established with [AF_INET]88.77.66.22:54344
Dec 12 12:19:41 VPN ovpn-Serveur[355]: 172.16.1.100 TCP connection established with [AF_INET]88.77.66.22
```
Before, the last digit of port (4 of 56364, or 4 of 54344) was not colored
=> conf.log : the port of "172.16.1.100:56364" is now fully colored

grc.zsh
The current `grc.zsh` alias declarations overwrite the completions helper from zsh.
With wrapping the grc call as a function, the completion system still works.
More description available on github thread:
https://github.com/ohmyzsh/ohmyzsh/issues/6954
=> Add completions for aliases when defined for zsh.
